---
name: "Integration tests with CML - libssh ðŸ’»"
on:
  pull_request_target:
    branches: [main]
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - "plugins/**"
      - "tests/integration/**"
  workflow_dispatch:
jobs:
  lab-create:
    uses: nickbhasin/ansible-content-actions/.github/workflows/cml_lab_create.yaml@cml_httpapi_support
    with:
      topology_path: tests/integration/labs/multi.yaml
      # lab_title_override: "Optional custom lab title"
    secrets:
      virl_host: ${{ secrets.VIRL_HOST }}
      virl_username: ${{ secrets.VIRL_USERNAME }}
      virl_password: ${{ secrets.VIRL_PASSWORD }}

  integration-tests-libssh:
    needs: lab-create
    strategy:
      fail-fast: true
      matrix:
        ansible_version: ["stable-2.16", "stable-2.18", "stable-2.19", "milestone", "devel"]
    uses: nickbhasin/ansible-content-actions/.github/workflows/cml_network_integration.yaml@cml_httpapi_support
    with:
      ansible_version: ${{ matrix.ansible_version }}
      lab_nodes: ${{ needs.lab-create.outputs.lab_nodes_json }}

  lab-destroy:
    if: ${{ always() }}
    needs: integration-tests-libssh
    uses: nickbhasin/ansible-content-actions/.github/workflows/cml_lab_destroy.yaml@cml_httpapi_support
    secrets:
      virl_host: ${{ secrets.VIRL_HOST }}
      virl_username: ${{ secrets.VIRL_USERNAME }}
      virl_password: ${{ secrets.VIRL_PASSWORD }}
